Feature/develop create recipe flow
mif-az/Ultra-Saver pull request #47
Opened 2022-10-08 13:52 UTC by onlyidev

- Full CRUD for recipes
- Pagination
- Search recipes by name (closes #32)
- Minor migration updates

2022-10-08 13:55 UTC, onlyidev commented on Controllers/RecipeController.cs
> +    public IActionResult getRecipies(uint page = 1, string? filter = null) // Query parameter with default value
Closes #50

2022-10-08 14:02 UTC, onlyidev commented on Controllers/RecipeController.cs
> +        return Ok(_db.Recipes.Skip(((int)(page) - 1) * AppDatabaseContext.ItemsPerPage).Take(AppDatabaseContext.ItemsPerPage));
Closes #54 (widening part as `page` is of type `uint`)

2022-10-08 14:02 UTC, onlyidev commented on Controllers/RecipeController.cs
> +        return Ok(_db.Recipes.Skip(((int)(page) - 1) * AppDatabaseContext.ItemsPerPage).Take(AppDatabaseContext.ItemsPerPage));
Closes #55

2022-10-08 14:09 UTC, onlyidev commented on Controllers/RecipeController.cs
> +    public IActionResult getRecipies(uint page = 1, string? filter = null) // Query parameter with default value
Optional and named argument usage

2022-10-08 14:14 UTC, onlyidev commented on Controllers/RecipeController.cs
> +    public IActionResult getRecipies(uint page = 1, string? filter = null) // Query parameter with default value
Closes #50

2022-10-08 14:15 UTC, onlyidev commented
Closes:
- #50

2022-10-08 14:22 UTC, onlyidev reviewed
Requirement implementations

2022-10-08 14:22 UTC, onlyidev commented on Controllers/RecipeController.cs
> +            string str = filter.map(letter => $".*?{Regex.Escape(letter.ToString().ToLower())}.*?");
Regex usage

2022-10-08 14:22 UTC, onlyidev commented on Controllers/RecipeController.cs
> +        return Ok(_db.Recipes.Skip(((int)(page) - 1) * AppDatabaseContext.ItemsPerPage).Take(AppDatabaseContext.ItemsPerPage));
LINQ usage

2022-10-08 14:22 UTC, onlyidev commented on Controllers/RecipeController.cs
> +        return Ok(_db.Recipes.Skip(((int)(page) - 1) * AppDatabaseContext.ItemsPerPage).Take(AppDatabaseContext.ItemsPerPage));
Type conversions widening part

2022-10-08 14:22 UTC, onlyidev commented on Controllers/RecipeController.cs
> +                && (recipe = _db.Recipes.Find((int)data.id.Value)) != null
Type conversions narrowing part

2022-10-09 19:20 UTC, Storas008 commented on Controllers/RecipeController.cs
> +    public IActionResult getRecipies(uint page = 1, string? filter = null) // Query parameter with default value
must use PascalCase, please change to GetRecipies();

2022-10-09 19:21 UTC, Storas008 commented on Controllers/RecipeController.cs
> +    public IActionResult upsertRecipe(RecipeModel recipe) //For upserting we need the full model information (id can be ommited for creating a new recipe)
Please change to UpsertRecipe();

2022-10-09 19:22 UTC, Storas008 commented on Controllers/RecipeController.cs
> +    public IActionResult deleteRecipe([FromBody] dynamic req) // We only need the id of the recipe
change to PascalCase

2022-10-09 19:53 UTC, Storas008 requested changes
Everything seems right (lol), just need some very minor changes.

2022-10-09 20:12 UTC, Storas008 approved these changes

2022-10-09 20:13 UTC, merged